/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { CrossrefClient } from './CrossrefClient';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { Affiliation } from './models/Affiliation';
export type { Agency } from './models/Agency';
export type { AgencyMessage } from './models/AgencyMessage';
export type { Author } from './models/Author';
export type { Coverage } from './models/Coverage';
export type { CoverageFull } from './models/CoverageFull';
export type { Date } from './models/Date';
export type { DateParts } from './models/DateParts';
export type { Deposit } from './models/Deposit';
export type { DepositMessage } from './models/DepositMessage';
export type { Deposits } from './models/Deposits';
export type { DepositsMessage } from './models/DepositsMessage';
export type { DoiAgency } from './models/DoiAgency';
export type { DoiCounts } from './models/DoiCounts';
export type { Flags } from './models/Flags';
export type { Funder } from './models/Funder';
export type { FunderFull } from './models/FunderFull';
export type { FunderHierarchy } from './models/FunderHierarchy';
export type { FunderMessage } from './models/FunderMessage';
export type { FunderMessageMessageHierarchyJava_lang_string39106 } from './models/FunderMessageMessageHierarchyJava_lang_string39106';
export type { FunderMessageMessageHierarchyNames } from './models/FunderMessageMessageHierarchyNames';
export type { Funders } from './models/Funders';
export type { FundersMessage } from './models/FundersMessage';
export type { Journal } from './models/Journal';
export type { JournalIssnType } from './models/JournalIssnType';
export type { JournalMessage } from './models/JournalMessage';
export type { JournalMessageMessageBreakdowns } from './models/JournalMessageMessageBreakdowns';
export type { JournalMessageMessageCoverageType } from './models/JournalMessageMessageCoverageType';
export type { Journals } from './models/Journals';
export type { JournalsMessage } from './models/JournalsMessage';
export type { JournalsMessageMessageItemsBreakdowns } from './models/JournalsMessageMessageItemsBreakdowns';
export type { JournalsMessageMessageItemsCoverageType } from './models/JournalsMessageMessageItemsCoverageType';
export type { License } from './models/License';
export type { Licenses } from './models/Licenses';
export type { LicensesMessage } from './models/LicensesMessage';
export type { Member } from './models/Member';
export type { MemberMessage } from './models/MemberMessage';
export type { MemberMessageMessageBreakdowns } from './models/MemberMessageMessageBreakdowns';
export type { MemberMessageMessageCountsType } from './models/MemberMessageMessageCountsType';
export type { MemberMessageMessageCountsTypeAll } from './models/MemberMessageMessageCountsTypeAll';
export type { MemberMessageMessageCountsTypeBackfile } from './models/MemberMessageMessageCountsTypeBackfile';
export type { MemberMessageMessageCountsTypeCurrent } from './models/MemberMessageMessageCountsTypeCurrent';
export type { MemberMessageMessageCoverageType } from './models/MemberMessageMessageCoverageType';
export type { MemberMessageMessageCoverageTypeAll } from './models/MemberMessageMessageCoverageTypeAll';
export type { MemberMessageMessageCoverageTypeBackfile } from './models/MemberMessageMessageCoverageTypeBackfile';
export type { MemberMessageMessageCoverageTypeCurrent } from './models/MemberMessageMessageCoverageTypeCurrent';
export type { MemberPrefix } from './models/MemberPrefix';
export type { Members } from './models/Members';
export type { MembersMessage } from './models/MembersMessage';
export type { MembersMessageMessageItemsBreakdowns } from './models/MembersMessageMessageItemsBreakdowns';
export type { MembersMessageMessageItemsCountsType } from './models/MembersMessageMessageItemsCountsType';
export type { MembersMessageMessageItemsCountsTypeAll } from './models/MembersMessageMessageItemsCountsTypeAll';
export type { MembersMessageMessageItemsCountsTypeBackfile } from './models/MembersMessageMessageItemsCountsTypeBackfile';
export type { MembersMessageMessageItemsCountsTypeCurrent } from './models/MembersMessageMessageItemsCountsTypeCurrent';
export type { MembersMessageMessageItemsCoverageType } from './models/MembersMessageMessageItemsCoverageType';
export type { MembersMessageMessageItemsCoverageTypeAll } from './models/MembersMessageMessageItemsCoverageTypeAll';
export type { MembersMessageMessageItemsCoverageTypeBackfile } from './models/MembersMessageMessageItemsCoverageTypeBackfile';
export type { MembersMessageMessageItemsCoverageTypeCurrent } from './models/MembersMessageMessageItemsCoverageTypeCurrent';
export type { Prefix } from './models/Prefix';
export type { PrefixMessage } from './models/PrefixMessage';
export type { Query } from './models/Query';
export type { Reference } from './models/Reference';
export type { Type } from './models/Type';
export type { TypeMessage } from './models/TypeMessage';
export type { Types } from './models/Types';
export type { TypesMessage } from './models/TypesMessage';
export type { Work } from './models/Work';
export type { WorkAssertion } from './models/WorkAssertion';
export type { WorkClinicalTrial } from './models/WorkClinicalTrial';
export type { WorkDomain } from './models/WorkDomain';
export type { WorkFreeToRead } from './models/WorkFreeToRead';
export type { WorkFunder } from './models/WorkFunder';
export type { WorkInstitution } from './models/WorkInstitution';
export type { WorkISSNType } from './models/WorkISSNType';
export type { WorkJournalIssue } from './models/WorkJournalIssue';
export type { WorkLicense } from './models/WorkLicense';
export type { WorkLink } from './models/WorkLink';
export type { WorkMessage } from './models/WorkMessage';
export type { WorkMessageMessageAssertionExplanation } from './models/WorkMessageMessageAssertionExplanation';
export type { WorkMessageMessageAssertionGroup } from './models/WorkMessageMessageAssertionGroup';
export type { WorkMessageMessageRelationJava_lang_string39107 } from './models/WorkMessageMessageRelationJava_lang_string39107';
export type { WorkRelation } from './models/WorkRelation';
export type { WorkReview } from './models/WorkReview';
export type { Works } from './models/Works';
export type { WorksMessage } from './models/WorksMessage';
export type { WorksMessageMessageItemsAssertionExplanation } from './models/WorksMessageMessageItemsAssertionExplanation';
export type { WorksMessageMessageItemsAssertionGroup } from './models/WorksMessageMessageItemsAssertionGroup';
export type { WorksMessageMessageItemsRelationJava_lang_string39101 } from './models/WorksMessageMessageItemsRelationJava_lang_string39101';
export type { WorksMessageMessageItemsRelationJava_lang_string39102 } from './models/WorksMessageMessageItemsRelationJava_lang_string39102';
export type { WorksMessageMessageItemsRelationJava_lang_string39103 } from './models/WorksMessageMessageItemsRelationJava_lang_string39103';
export type { WorksMessageMessageItemsRelationJava_lang_string39104 } from './models/WorksMessageMessageItemsRelationJava_lang_string39104';
export type { WorksMessageMessageItemsRelationJava_lang_string39108 } from './models/WorksMessageMessageItemsRelationJava_lang_string39108';
export type { WorksMessageMessageItemsRelationJava_lang_string39109 } from './models/WorksMessageMessageItemsRelationJava_lang_string39109';
export type { WorkStandardsBody } from './models/WorkStandardsBody';
export type { WorkUpdate } from './models/WorkUpdate';

export { DepositsService } from './services/DepositsService';
export { FundersService } from './services/FundersService';
export { JournalsService } from './services/JournalsService';
export { LicensesService } from './services/LicensesService';
export { MembersService } from './services/MembersService';
export { PrefixesService } from './services/PrefixesService';
export { TypesService } from './services/TypesService';
export { WorksService } from './services/WorksService';
